function bareNPA10xCRRSGSubBG = import_singlePoint(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  BARENPA10XCRRSGSUBBG = IMPORTFILE1(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  BARENPA10XCRRSGSUBBG = IMPORTFILE1(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  bareNPA10xCRRSGSubBG = importfile1("C:\Users\eliez\Desktop\Ben-Protein Data_r1\1_bare NPA 10x (CRR) (SG) (Sub BG).txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-May-2025 10:33:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["XAxis", "bareNPA10xCRRSGSubBG"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
bareNPA10xCRRSGSubBG = readtable(filename, opts);

%% Convert to output type
bareNPA10xCRRSGSubBG = table2array(bareNPA10xCRRSGSubBG);
end